### ISSUE TITLE
RealtimeClient.ParseMessage is private

### ISSUE THREAD

**Issue by nsxdavid** [sefbkn/gdax.netcore#12]
https://github.com/sefbkn/gdax.netcore/blob/b39d93b52efad3f6e43652065c4594725fd74ed7/src/Api/Clients/RealtimeClient.cs#L90

RealtimeClient.ParseMessage should be public so you can parse the incoming feed (which comes in as strings to the callback action).

**Comment by sefbkn** [comment]
@nsxdavid Taken care of, thank you for pointing this out.
