### ISSUE TITLE
Looks like there is an error in RequestAuthenticator -> GetAuthenticationToken parameter order

### ISSUE THREAD

**Issue by phclem** [sefbkn/gdax.netcore#6]
public AuthenticationToken GetAuthenticationToken(ApiRequest request)
        {
            var timestamp = (request.Timestamp).ToString(System.Globalization.CultureInfo.InvariantCulture);
            var signature = ComputeSignature(request);
            // the following construction has the parameters specified in an incorrect order
            // return new AuthenticationToken(_apiKey, signature, timestamp, _passphrase);
            // should be
            return new AuthenticationToken(_apiKey, _passphrase, signature, timestamp);
        }

**Comment by markwkjr** [comment]
@phclem I fixed this commit [284bba8c6f4efb2a3576659a346d52efbbe1cc0b](https://github.com/markwkjr/gdax.netcore/commit/284bba8c6f4efb2a3576659a346d52efbbe1cc0b). It has a bunch of other changes that I'm not sure are ready for a PR yet though :-/
It adds support for the PostOnly option in ordering, which I have tested and works. And then it has some unfinished code I was working on to support the [Candles Endpoint](https://github.com/sefbkn/gdax.netcore/issues/5)
