### ISSUE TITLE
await keyword in example is throwing an error

### ISSUE THREAD

**Issue by UniversalAE** [sefbkn/gdax.netcore#8]
Here's the entire program:

using System;
using System.Net;
using Boukenken.Gdax;

namespace GDAXtest
{
    class Program
    {
        static void Main(string[] args)
        {
			var baseUrl = "https://api.gdax.com/";
			var apiKey = "<api-key>";
			var secret = "<secret>";
			var passphrase = "<passphrase>";

			var requestAuthenticator = new RequestAuthenticator(apiKey, passphrase, secret);
			var productClient = new ProductClient(baseUrl, requestAuthenticator);
			var productResponse = await productClient.GetProductTickerAsync("BTC-USD");

			if (productResponse.StatusCode == HttpStatusCode.OK)
			{
				var ticker = productResponse.Value;
				Console.WriteLine("Price: {0}", ticker.price);
			}
		}
    }
}

Throws this compiler error:

Error	CS4033	The 'await' operator can only be used within an async method. Consider marking this method with the 'async' modifier and changing its return type to 'Task'.

I'm boggled because I believe your library defines GetProductTickerAsync properly with the async modifier.   Is there something I am missing in the usage of your example?

**Comment by sefbkn** [comment]
Main isn't async, although if you try to make Main async you'll run into another compiler error.

The solution here is for you to wrap the rest of your code in an async method,

    public static async Task MyMethodAsync(){ ... var requestAuthenticator ... }

call that method from main and call .Result on the return value.

    public static void Main(string[] args) { ... MyMethodAsync().Result; ... }
